const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')

test('production admin uses CloudBase Web Auth and Event Function without a gateway', () => {
  const appSource = fs.readFileSync(path.join(root, 'src/App.tsx'), 'utf8')
  const authSource = fs.readFileSync(path.join(root, 'src/cloudbase-auth.ts'), 'utf8')
  const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
  const releaseSource = fs.readFileSync(path.join(root, 'scripts/check-release-readiness.cjs'), 'utf8')
  const adminDoc = fs.readFileSync(path.join(root, 'docs/web-admin.md'), 'utf8')

  assert.match(appSource, /const isConfigured = Boolean\(cloudbaseApp \|\| API_BASE\)/)
  assert.match(appSource, /if \(cloudbaseApp\) \{\s*return callAdminFunction<T>\(action, payload\)/)
  assert.match(authSource, /import\.meta\.env\.DEV && import\.meta\.env\.MODE === 'local-admin'/)
  assert.equal(packageJson.scripts['dev:local'], 'vite --mode local-admin')
  assert.match(releaseSource, /VITE_CLOUDBASE_ENV_ID/)
  assert.doesNotMatch(fs.readFileSync(path.join(root, 'cloudfunctions/adminApi/index.js'), 'utf8'), /generatedByAdminId:\s*payload\.generatedByAdminId/)
  assert.doesNotMatch(releaseSource, /VITE_ADMIN_API_BASE/)
  assert.match(releaseSource, /VITE_CLOUDBASE_PUBLISHABLE_KEY/)
  assert.match(releaseSource, /ADMIN_WEB_AUTH_E2E_PASSED/)
  assert.match(fs.readFileSync(path.join(root, 'cloudfunctions/adminApi/index.js'), 'utf8'), /DEFAULT_ADMIN_AUTH_UID/)
  assert.doesNotMatch(adminDoc, /VITE_ADMIN_API_BASE|ADMIN_WEB_TOKEN|VITE_ADMIN_API_TOKEN/)
  assert.match(adminDoc, /CloudBase Web Auth/)
  assert.match(adminDoc, /Event Function/)
})
