import type { AppData } from './types'

export const SAFETY_NOTICE =
  '本系统仅用于家庭健康记录、历史信息查询和医嘱整理，不提供疾病诊断、处方建议或剂量调整建议。用药请遵医嘱或咨询医生/药师；如症状加重或出现紧急情况，请及时就医。'

export const STORAGE_KEY = 'family-health-box:v1'

export const defaultData: AppData = {
  familyName: '我的家庭健康记录',
  members: [
    {
      id: 'member-child',
      name: '小安',
      relation: '孩子',
      birthday: '2018-06-18',
      gender: 'female',
      allergyHistory: '青霉素过敏待确认',
      medicalHistory: '换季鼻炎、偶发咳嗽',
      note: '优先记录体温、症状变化和医生医嘱',
      createdAt: '2026-05-11T09:00:00.000Z',
    },
    {
      id: 'member-mom',
      name: '妈妈',
      relation: '妈妈',
      birthday: '1991-03-02',
      gender: 'female',
      allergyHistory: '暂无',
      medicalHistory: '偏头痛',
      note: '家庭健康记录主要维护人',
      createdAt: '2026-05-11T09:05:00.000Z',
    },
  ],
  medicines: [
    {
      id: 'medicine-fever',
      name: '对乙酰氨基酚混悬液',
      category: '退烧',
      specification: '100ml/瓶',
      totalQuantity: 100,
      remainingQuantity: 62,
      unit: 'ml',
      expireDate: '2026-08-20',
      location: '客厅常备区上层',
      source: '常备',
      indicationsText: '家庭记录：曾用于儿童发热场景，具体使用以医生医嘱和说明书为准',
      instructionText: '按医生医嘱或药品说明书使用，不在系统内自动判断剂量',
      note: '开封日期需另行标记',
      createdAt: '2026-05-11T09:10:00.000Z',
      updatedAt: '2026-05-11T09:10:00.000Z',
    },
    {
      id: 'medicine-cough',
      name: '生理盐水鼻喷',
      category: '鼻炎',
      specification: '60ml/瓶',
      totalQuantity: 60,
      remainingQuantity: 18,
      unit: 'ml',
      expireDate: '2026-06-18',
      location: '儿童护理抽屉',
      source: '自购',
      indicationsText: '家庭记录：鼻塞时辅助清洁',
      instructionText: '按说明书使用',
      note: '库存偏低，可检查是否需要补充',
      createdAt: '2026-05-11T09:12:00.000Z',
      updatedAt: '2026-05-11T09:12:00.000Z',
    },
    {
      id: 'medicine-stomach',
      name: '口服补液盐',
      category: '腹泻',
      specification: '5袋/盒',
      totalQuantity: 5,
      remainingQuantity: 5,
      unit: '袋',
      expireDate: '2027-01-10',
      location: '客厅常备区下层',
      source: '常备',
      indicationsText: '家庭记录：腹泻、呕吐后补液相关医嘱曾提及',
      instructionText: '按医生医嘱或说明书冲调',
      note: '儿童使用前确认医嘱',
      createdAt: '2026-05-11T09:14:00.000Z',
      updatedAt: '2026-05-11T09:14:00.000Z',
    },
  ],
  illnessRecords: [
    {
      id: 'illness-cough-1',
      memberId: 'member-child',
      startedAt: '2026-04-21T19:30',
      endedAt: '2026-04-27T20:00',
      symptoms: ['咳嗽', '鼻塞'],
      symptomDescription: '夜间咳嗽明显，白天精神尚可，无高热记录。',
      temperatureMax: 37.6,
      hospitalName: '社区儿科门诊',
      doctorDiagnosis: '医生记录：上呼吸道感染观察',
      doctorAdvice: '多饮水，观察精神状态；如高热不退或呼吸异常及时复诊。',
      examinationResult: '未做特殊检查',
      status: '已恢复',
      summary: '约 6 天恢复，主要记录鼻塞和夜间咳嗽变化。',
      createdAt: '2026-05-11T09:20:00.000Z',
      updatedAt: '2026-05-11T09:20:00.000Z',
    },
    {
      id: 'illness-fever-1',
      memberId: 'member-child',
      startedAt: '2026-05-05T22:10',
      endedAt: '',
      symptoms: ['发热', '咽痛'],
      symptomDescription: '夜间发热，第二天上午退热，仍需观察咽痛。',
      temperatureMax: 38.7,
      hospitalName: '',
      doctorDiagnosis: '',
      doctorAdvice: '家庭观察记录，未录入医生医嘱。',
      examinationResult: '',
      status: '观察中',
      summary: '已记录一次退热药使用，后续补充体温变化。',
      createdAt: '2026-05-11T09:22:00.000Z',
      updatedAt: '2026-05-11T09:22:00.000Z',
    },
  ],
  medicationLogs: [
    {
      id: 'log-fever-1',
      memberId: 'member-child',
      illnessRecordId: 'illness-fever-1',
      medicineId: 'medicine-fever',
      medicineNameSnapshot: '对乙酰氨基酚混悬液',
      doseQuantity: 5,
      doseUnit: 'ml',
      takenAt: '2026-05-05T22:30',
      frequencyText: '单次记录',
      wasPlanned: true,
      reaction: '约 1 小时后体温下降，精神好转',
      note: '剂量来自当次医嘱/说明书核对后的家庭记录',
      createdAt: '2026-05-11T09:30:00.000Z',
    },
  ],
}
